#!/usr/bin/env bash
# Generates a small, deterministic sample directory tree for the VHS demos to
# browse. Regenerated by `make demos` and removed afterward, so the GIFs look
# identical on every machine. Safe to run standalone: bash docs/demo/fixture.sh
set -euo pipefail

# Generate at a neutral path (outside the repo / home dir) so the picker's
# breadcrumb in the recordings reads cleanly, e.g. "/tmp/rummage-demo", instead
# of leaking a real home path. Override by passing a path as $1.
root="${1:-/tmp/rummage-demo}"

rm -rf "$root"
mkdir -p "$root/internal" "$root/docs" "$root/assets"

cat > "$root/README.md" <<'EOF'
# Acme Service

A small example project used to demo the rummage picker.

## Features
- Fast startup
- Pluggable storage
- Structured logging

## Getting started
    go run ./...
EOF

cat > "$root/main.go" <<'EOF'
package main

import "fmt"

func main() {
	fmt.Println("acme service starting...")
	srv := NewServer(":8080")
	srv.ListenAndServe()
}
EOF

cat > "$root/server.go" <<'EOF'
package main

// Server handles incoming requests.
type Server struct{ addr string }

func NewServer(addr string) *Server { return &Server{addr: addr} }

func (s *Server) ListenAndServe() error { return nil }
EOF

cat > "$root/handlers.go" <<'EOF'
package main

func handleHealth() string { return "ok" }
func handleIndex() string  { return "acme" }
EOF

cat > "$root/config.go" <<'EOF'
package main

type Config struct {
	Addr    string
	Verbose bool
}
EOF

cat > "$root/notes.txt" <<'EOF'
TODO: wire up metrics, add graceful shutdown, document the API.
EOF

printf 'module acme\n\ngo 1.25\n'        > "$root/go.mod"
printf 'build:\n\tgo build ./...\n'       > "$root/Makefile"

cat > "$root/internal/store.go" <<'EOF'
package internal

type Store interface {
	Get(key string) ([]byte, error)
	Put(key string, val []byte) error
}
EOF

cat > "$root/internal/cache.go" <<'EOF'
package internal

type Cache struct{ entries map[string][]byte }
EOF

printf '# Guide\n\nHow to operate the service.\n'        > "$root/docs/guide.md"
printf '# Architecture\n\nLayers: api, core, store.\n'   > "$root/docs/architecture.md"
printf 'ACME\n====\n'                                    > "$root/assets/logo.txt"

# Hidden files (only shown with -hidden) — present so that demo can be extended.
printf 'TOKEN=changeme\n' > "$root/.env"
printf 'bin/\n*.log\n'    > "$root/.gitignore"

echo "fixture ready: $root"
